### ISSUE TITLE
I Got 401

### ISSUE THREAD

**Issue by mosageneral** [xshaheen/xdot-paymob#122]
### Describe the bug

i did all the steps in the describtion but got  Paymob Cash In - Http request failed with status code (401).

### Steps to reproduce

nothing just run the code 
var amountCents = 1000; // 10 LE
			var orderRequest = CashInCreateOrderRequest.CreateOrder(amountCents);
			var orderResponse = await _broker.CreateOrderAsync(orderRequest);

			// Request card payment key.
			var billingData = new CashInBillingData(
				firstName: "Mahmoud",
				lastName: "Shaheen",
				phoneNumber: "010000000",
				email: "mxshaheen@gmail.com");

			var paymentKeyRequest = new CashInPaymentKeyRequest(
				integrationId: 123,
				orderId: orderResponse.Id,
				billingData: billingData,
				amountCents: amountCents);

			var paymentKeyResponse = await _broker.RequestPaymentKeyAsync(paymentKeyRequest);

			// Create iframe src.
			return _broker.CreateIframeSrc(iframeId: "776060", token: paymentKeyResponse.PaymentKey);

### Expected behaviour

it should return iframe link

**Comment by xshaheen** [comment]
Do you configure your ApiKey and your Hmac correctly using

```cs
services.AddPaymobCashIn(config => {
    config.ApiKey = "Api Key";
    config.Hmac = "Hmac secret",
});
```

**Comment by mosageneral** [comment]
it was integrationid mistake not it's working
